<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

use Netopia\Payment\Address;
use Netopia\Payment\Invoice;
use Netopia\Payment\Request\Card;
use Netopia\Payment\Request\Notify;
use Netopia\Payment\Request\PaymentAbstract;

// use Illuminate\Support\Facades\Redirect;

class PlataOnlineController extends Controller
{
    /**
     * all payment requests will be sent to the NETOPIA Payments server
     * SANDBOX : http://sandboxsecure.mobilpay.ro
     * LIVE : https://secure.mobilpay.ro
     */
    public $paymentUrl;
    /**
     * NETOPIA Payments is working only with Certificate. Each NETOPIA partner (merchant) has a certificate.
     * From your Admin panel you can download the Certificate.
     * is located in Admin -> Conturi de comerciant -> Detalii -> Setari securitate
     * the var $x509FilePath is path of your certificate in your platform
     * i.e: /home/certificates/public.cer
     */
    public $x509FilePath;
    /**
     * Billing Address
     */
    public $billingAddress;
    /**
     * Shipping Address
     */
    public $shippingAddress;


    /**
     * Variabile pentru raspuns
     */
    public $errorCode;
    public $errorType;
    public $errorMessage;   

    
    public function trimitereCatrePlata()
    {
        $this->paymentUrl   = config('mobilpay.payment_url', '');
        $this->x509FilePath = config('mobilpay.public_key_path', '');
        try {
            $paymentRequest = new Card();
            $paymentRequest->signature  = config('mobilpay.merchant_id', '');//signature - generated by mobilpay.ro for every merchant account
            $paymentRequest->orderId    = md5(uniqid(rand())); // order_id should be unique for a merchant account
            // $paymentRequest->orderId    = 6; // order_id should be unique for a merchant account
            $paymentRequest->confirmUrl = config('mobilpay.confirm_url', ''); // is where mobilPay redirects the client once the payment process is finished and is MANDATORY
            $paymentRequest->returnUrl  = config('mobilpay.return_url', '');;// is where mobilPay will send the payment result and is MANDATORY

            /*
             * Adaugarea de campuri proprii in cererea de plata
             */
            $paymentRequest->params = array (
                // 'var1'=>$val1,
                // 'var2'=>$val2
                'rezervare_id'=>6
            );

            /*
             * Invoices info
             */
            $paymentRequest->invoice = new Invoice();
            $paymentRequest->invoice->currency  = 'RON';
            $paymentRequest->invoice->amount    = '1.00';
            $paymentRequest->invoice->tokenId   = null;
            $paymentRequest->invoice->details   = "Payment Via Composer library";

            /*
             * Billing Info
             */
            $this->billingAddress = new Address();
            $this->billingAddress->type         = "person"; //should be "person" / "company"
            $this->billingAddress->firstName    = "Billing name";
            $this->billingAddress->lastName     = "Billing LastName";
            $this->billingAddress->address      = "Bulevardul Ion Creangă, Nr 00";
            $this->billingAddress->email        = "test@billing.com";
            $this->billingAddress->mobilePhone  = "0732123456";
            $paymentRequest->invoice->setBillingAddress($this->billingAddress);

            /*
             * Shipping
             */
            $this->shippingAddress = new Address();
            $this->shippingAddress->type        = "person"; //should be "person" / "company"
            $this->shippingAddress->firstName   = "Shipping Name";
            $this->shippingAddress->lastName    = "Shipping LastName";
            $this->shippingAddress->address     = "Bulevardul Mihai Eminescu, Nr 00";
            $this->shippingAddress->email       = "test@shipping.com";
            $this->shippingAddress->mobilePhone = "0721234567";
            $paymentRequest->invoice->setShippingAddress($this->shippingAddress);

            /*
             * encrypting
             */
            $paymentRequest->encrypt($this->x509FilePath);

            /**
             * send the following data to NETOPIA Payments server
             * Method : POST
             * URL : $paymentUrl
             */
            $EnvKey = $paymentRequest->getEnvKey();
            $data   = $paymentRequest->getEncData();


            $paymentUrl = $this->paymentUrl;
            return view('plata-online.redirect', compact('paymentUrl', 'EnvKey', 'data'));
            
        }catch (\Exception $e)
        {
            return "Oops, There is a problem!";
        }
    }      
    
    public function confirmarePlata()
    {    
        $this->errorType = PaymentAbstract::CONFIRM_ERROR_TYPE_NONE;
        $this->errorCode = 0;
        $this->errorMessage = '';

        $this->paymentUrl = config('mobilpay.payment_url', '');
        $this->x509FilePath = config('mobilpay.private_key_path', '');

// DB::table('plata_online')->insert([
//                         'nume' => strcasecmp($_SERVER['REQUEST_METHOD'], 'post'),
//                         'telefon' => isset($_POST['env_key']),
//                         'email' => isset($_POST['data']),
//                         // 'adresa' => $data['objPmNotify']['customer']['address'],
//                         'created_at' => \Carbon\Carbon::now(),
//                     ]);

        if (strcasecmp($_SERVER['REQUEST_METHOD'], 'post') == 0){
            if(isset($_POST['env_key']) && isset($_POST['data'])){
                try {
                    $paymentRequestIpn = PaymentAbstract::factoryFromEncrypted($_POST['env_key'],$_POST['data'],$this->x509FilePath);
                    $rrn = $paymentRequestIpn->objPmNotify->rrn;
                    
                    // $plata_online = DB::table('plata_online')->where('rezervare_id', $paymentRequestIpn->objPmReq->params['rezervare_id'])->first();
                    // DB::table('rezervari')->where('id', $plata_online->rezervare_id)->update(['plata_efectuata' => 1]);                    
                    // DB::table('rezervari')->where('id', 6)->update(['plata_efectuata' => 1]);                    

                    if ($paymentRequestIpn->objPmNotify->errorCode == 0) {
                        switch($paymentRequestIpn->objPmNotify->action){
                            case 'confirmed':
                                //update DB, SET status = "confirmed/captured"
                                $this->errorMessage = $paymentRequestIpn->objPmNotify->errorMessage;
                                $mesaj_personalizat = 'Tranzacția a fost efectuată';
                                break;
                            case 'confirmed_pending':
                                //update DB, SET status = "pending"
                                $this->errorMessage = $paymentRequestIpn->objPmNotify->errorMessage;
                                $mesaj_personalizat = 'Tranzacția este în curs de revizuire. După acest lucru, o nouă solicitare IPN va fi trimisă fie cu confirmare, fie cu anulare (confirmed_pending)';
                                break;
                            case 'paid_pending':
                                //update DB, SET status = "pending"
                                $this->errorMessage = $paymentRequestIpn->objPmNotify->errorMessage;
                                $mesaj_personalizat = 'Tranzacția este în curs de revizuire. După acest lucru, o nouă solicitare IPN va fi trimisă fie cu confirmare, fie cu anulare (paid_pending)';
                                break;
                            case 'paid':
                                //update DB, SET status = "open/preauthorized"
                                $this->errorMessage = $paymentRequestIpn->objPmNotify->errorMessage;
                                $mesaj_personalizat = 'Tranzacția este în curs de autorizare. După acest lucru, o nouă solicitare IPN va fi trimisă fie cu confirmare, fie cu anulare (paid)';
                                break;
                            case 'canceled':
                                //update DB, SET status = "canceled"
                                $this->errorMessage = $paymentRequestIpn->objPmNotify->errorMessage;
                                $mesaj_personalizat = 'Tranzacția a fost anulată';
                                break;
                            case 'credit':
                                //update DB, SET status = "refunded"
                                $this->errorMessage = $paymentRequestIpn->objPmNotify->errorMessage;
                                $mesaj_personalizat = 'Tranzacția a fost rambursată';
                                break;
                            default:
                                $errorType = PaymentAbstract::CONFIRM_ERROR_TYPE_PERMANENT;
                                $this->errorCode = PaymentAbstract::ERROR_CONFIRM_INVALID_ACTION;
                                $this->errorMessage = 'mobilpay_refference_action paramaters is invalid';
                                $mesaj_personalizat = $this->errorMessage;
                        }
                    }else{
                        //update DB, SET status = "rejected"
                        $this->errorMessage = $paymentRequestIpn->objPmNotify->errorMessage;
                        $mesaj_personalizat = 'Tranzacția a fost respinsă';
                    }
                }catch (\Exception $e) {
                    $this->errorType = PaymentAbstract::CONFIRM_ERROR_TYPE_TEMPORARY;
                    $this->errorCode = $e->getCode();
                    $this->errorMessage = $e->getMessage();
                    $mesaj_personalizat = $this->errorMessage;
    }

            }else{
                $this->errorType = PaymentAbstract::CONFIRM_ERROR_TYPE_PERMANENT;
                $this->errorCode = PaymentAbstract::ERROR_CONFIRM_INVALID_POST_PARAMETERS;
                $this->errorMessag = 'mobilpay.ro posted invalid parameters';
                $mesaj_personalizat = $this->errorMessag;
            }

        } else {
            $this->errorType = PaymentAbstract::CONFIRM_ERROR_TYPE_PERMANENT;
            $this->errorCode = PaymentAbstract::ERROR_CONFIRM_INVALID_POST_METHOD;
            $this->errorMessage = 'invalid request metod for payment confirmation';
            $mesaj_personalizat = $this->errorMessage;
        }

        /**
         * Communicate with NETOPIA Payments server
         */

        header('Content-type: application/xml');
        echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n";
        if($this->errorCode == 0)
        {
            echo "<crc>{$this->errorMessage}</crc>";
        }
        else
        {
            echo "<crc error_type=\"{$this->errorType}\" error_code=\"{$this->errorCode}\">{$this->errorMessage}</crc>";
        }

        /**
         * Salvare in baza de date
         */
        
                    DB::table('plata_online')->insert([
                        // // 'order_id' => $data['orderId'],
                        // 'action' => $data['objPmNotify']['action'],
                        // 'error_code' => $data['objPmNotify']['errorCode'],
                        // 'error_message' => $data['objPmNotify']['errorMessage'],
                        // 'notify_date' => $data['objPmNotify']['timestamp'],
                        // 'original_amount' => $data['objPmNotify']['originalAmount'],
                        // 'processed_amount' => $data['objPmNotify']['processedAmount'],
                        // 'rezervare_id' => $data['params']['orderId'],
                        // 'nume' => $data['objPmNotify']['customer']['firstName'],
                        // 'telefon' => $data['objPmNotify']['customer']['mobilePhone'],
                        // 'email' => $data['objPmNotify']['customer']['email'],
                        // 'adresa' => $data['objPmNotify']['customer']['address'],
                        // 'created_at' => \Carbon\Carbon::now(),
                        'order_id' => $paymentRequestIpn->orderId ?? '',
                        'action' => $paymentRequestIpn->objPmNotify->action ?? '',
                        'error_code' => $this->errorCode ?? '',
                        'error_message' => $this->errorMessage ?? '',
                        'mesaj_personalizat' => $mesaj_personalizat ?? '',
                        // 'notify_date' => $data['objPmNotify']['timestamp'],
                        // 'original_amount' => $data['objPmNotify']['originalAmount'],
                        // 'processed_amount' => $data['objPmNotify']['processedAmount'],
                        'rezervare_id' => $paymentRequestIpn->objPmNotify->rezervare_id ?? '',
                        'nume' => $paymentRequestIpn->objPmNotify->params['rezervare_id'] ?? '',
                        'text' => json_encode($paymentRequestIpn) ?? '',
                        // 'nume' => $data['objPmNotify']['customer']['firstName'],
                        // 'telefon' => $data['objPmNotify']['customer']['mobilePhone'],
                        // 'email' => $data['objPmNotify']['customer']['email'],
                        // 'adresa' => $data['objPmNotify']['customer']['address'],
                        'created_at' => \Carbon\Carbon::now(),
                    ]);

    }
}
